### ISSUE TITLE
Ubuntu环境 leanticket执行lean up提示apikey value must be defined

### ISSUE THREAD

**Issue by cuirongqing** [leancloud/ticket#4]
按照步骤，执行到lean up时出错。
lean v:0.7.5
nodejs v: 4.2.6
npm v: 5.0.0
账号 cuirongqing
错误：
lean up
✓ 正在检测运行时
✓ 检测到 node.js 运行时
✓ 获取应用信息
✓ 当前应用：Test (pNWeH0jxky8mcNIV75wUBpCI-gzGzoHsz)
✓ 获取运引擎分组 web 信息
✓ 项目已启动，请使用浏览器访问：http://localhost:3000
✓ 云函数调试服务已启动，请使用浏览器访问：http://localhost:3001

leanticket@1.0.0 dev /home/cuirongqing/gitcode/ticket
WEBPACK_DEV_SERVER=http://localhost:8080 nodemon --ignore modules server.js
[nodemon] 1.11.0
[nodemon] to restart at any time, enter rs
[nodemon] watching: .
[nodemon] starting node server.js
/home/cuirongqing/gitcode/ticket/node_modules/mailgun-js/lib/mailgun.js:15
throw new Error('apiKey value must be defined!'); 
^

Error: apiKey value must be defined!
at new Mailgun (/home/cuirongqing/gitcode/ticket/node_modules/mailgun-js/lib/mailgun.js:15:11)
at module.exports (/home/cuirongqing/gitcode/ticket/node_modules/mailgun-js/lib/mailgun.js:144:10)
at Object. (/home/cuirongqing/gitcode/ticket/api/mail.js:3:38)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object. (/home/cuirongqing/gitcode/ticket/api/notify.js:1:76)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object. (/home/cuirongqing/gitcode/ticket/api/Ticket.js:6:16)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)

[nodemon] app crashed - waiting for file changes before starting...

**Comment by sdjcw** [comment]
你好，因为该 ticket 涉及到很多和外部系统的交互，比如说发邮件，微信通知等，所以需要一些 key 的配置，这些配置都需要在云引擎控制台的设置页面增加环境变量，如果没有这些环境变量，ticket 运行会有问题。

具体需要哪些环境变量可以参考 https://github.com/leancloud/ticket/blob/master/config.js 文件。
